-- =======================================================
-- BECHARASCAPE SUPABASE INITIALIZATION SCRIPT
-- Copy and paste this script into your Supabase SQL Editor
-- =======================================================

-- 1. Create posts table
create table if not exists posts (
  id uuid default gen_random_uuid() primary key,
  slug text unique not null,
  title text not null,
  description text not null,
  content text not null,
  image text not null default '/paludarium.png',
  author text not null default 'Aquascaper',
  tags text[] not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create page_views table for analytics
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  slug text not null,
  ip_hash text not null,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table posts enable row level security;
alter table page_views enable row level security;

-- 4. Create RLS Policies
-- Allow anyone to read posts
create policy "Allow public read posts" on posts
  for select using (true);

-- Allow server-side service role to insert/modify posts
create policy "Allow service role all on posts" on posts
  using (true)
  with check (true);

-- Allow anyone to insert page views (for analytics)
create policy "Allow public insert page_views" on page_views
  for insert with check (true);

-- Allow server-side service role to read/delete page views
create policy "Allow read page_views" on page_views
  for select using (true);

-- 5. Insert initial sample posts (matching our existing production posts)
insert into posts (slug, title, description, content, image, author, tags)
values 
(
  'setting-up-low-tech-tank',
  'Setting up a Low Tech Planted Tank',
  'A beginner-friendly guide to setting up a beautiful planted aquarium without CO2 injection.',
  'Setting up a planted tank doesn''t have to be expensive or complicated. In this guide, we''ll walk through the process of creating a stunning "low tech" aquascape.

## What is a Low Tech Tank?
A low tech tank is an aquarium that relies on natural processes rather than pressurized CO2 and high-intensity lighting. It''s slower-growing, easier to maintain, and perfect for beginners!

### The Essentials
1. **Substrate**: Use a nutrient-rich soil capped with gravel or sand.
2. **Lighting**: A standard LED light (around 15-20 lumens per liter).
3. **Plants**: Choose hardy plants like Anubias, Java Fern, and Cryptocorynes.',
  '/paludarium.png',
  'LowTechMaster',
  array['Tutorials', 'Planted Tank', 'Low Tech']
),
(
  'guide-to-cichlid-tanks',
  'The Ultimate Guide to Cichlid Aquariums',
  'Discover how to set up a vibrant, high-energy African Cichlid aquarium with proper rockscaping, filtration, and water parameters.',
  'African Cichlids are some of the most colorful, active, and behaviorally fascinating fish you can keep in a home aquarium. Hailing from the Rift Lakes of East Africa—primarily Lake Malawi and Lake Tanganyika—these fish demand specific setups to thrive.

## Designing the Perfect Hardscape
Cichlids love rocks. In their native habitats, they live among rocky reefs, using cracks and crevices for shelter, breeding, and establishing territory.',
  '/cichlids.png',
  'LakeTanganyikaExplorer',
  array['cichlids', 'hardscape', 'setup-guide']
),
(
  'how-to-build-paludarium',
  'How to Build a Vertical Paludarium with a Circular Focal Point',
  'A step-by-step layout guide to building a lush vertical paludarium featuring terrestrial mosses, a waterfall, and a circular geometric frame.',
  'A paludarium blends the best of terrestrial and aquatic ecosystems, offering a home for both water-dwelling creatures and humidity-loving land plants. 

In this design guide, we explore how to construct a vertical setup that integrates a circular frame as a focal window, emphasizing the raw texture of rocky cliffs and flowing water.',
  '/paludarium.png',
  'MossArtisan',
  array['paludarium', 'moss', 'diy']
);

-- =======================================================
-- 6. Storage Bucket & Policies for Article Images Upload
-- =======================================================

-- Create storage bucket
insert into storage.buckets (id, name, public) 
values ('article-images', 'article-images', true)
on conflict (id) do nothing;

-- Allow public read access to images
drop policy if exists "Allow public read access" on storage.objects;
create policy "Allow public read access" on storage.objects 
  for select using (bucket_id = 'article-images');

-- Allow authenticated/service role to upload images
drop policy if exists "Allow service role upload" on storage.objects;
create policy "Allow service role upload" on storage.objects 
  for insert with check (bucket_id = 'article-images');

